import type { StoryFile } from "./types";

/**
 * The living room's shipped files (the story's Act 2 set). `bytes` are the
 * exact sizes on disk, so the loading screen can weight its progress before
 * anything arrives. Generated from `apps/web/public/story/v1/room/`; any
 * change to a file there bumps the `v1` path and this list together.
 *
 * Tiers: high and medium load the 1024 texture and lightmap set, low loads
 * the 512 set. Both share the geometry (`room.bin`) and the anchors.
 */
export const ROOM_BASE_URL = "/story/v1/room/";

export const ROOM_FILES: StoryFile[] = [
  {
    url: "/story/v1/room/anchors.json",
    bytes: 9326,
    kind: "json",
    group: "room",
    tiers: ["high", "medium", "low"],
  },
  {
    url: "/story/v1/room/lm/furniture-pendant.ktx2",
    bytes: 136077,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/furniture-practical.ktx2",
    bytes: 125327,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/furniture-sky.ktx2",
    bytes: 138764,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/shell-pendant.ktx2",
    bytes: 106187,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/shell-practical.ktx2",
    bytes: 97468,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/shell-sky.ktx2",
    bytes: 91553,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/table-pendant.ktx2",
    bytes: 161712,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/table-practical.ktx2",
    bytes: 151803,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm/table-sky.ktx2",
    bytes: 151913,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/lm-low/furniture-pendant.ktx2",
    bytes: 52882,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/furniture-practical.ktx2",
    bytes: 51181,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/furniture-sky.ktx2",
    bytes: 53408,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/shell-pendant.ktx2",
    bytes: 39970,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/shell-practical.ktx2",
    bytes: 36771,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/shell-sky.ktx2",
    bytes: 34211,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/table-pendant.ktx2",
    bytes: 54634,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/table-practical.ktx2",
    bytes: 51919,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/lm-low/table-sky.ktx2",
    bytes: 51770,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/room-low.gltf",
    bytes: 72504,
    kind: "gltf",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/room.bin",
    bytes: 350776,
    kind: "bin",
    group: "room",
    tiers: ["high", "medium", "low"],
  },
  {
    url: "/story/v1/room/room.gltf",
    bytes: 72402,
    kind: "gltf",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-a-color.ktx2",
    bytes: 221949,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-a-normal.ktx2",
    bytes: 8662,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-a-orm.ktx2",
    bytes: 28892,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-b-color.ktx2",
    bytes: 244017,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-b-normal.ktx2",
    bytes: 21401,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-b-orm.ktx2",
    bytes: 43673,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-c-color.ktx2",
    bytes: 238049,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-c-normal.ktx2",
    bytes: 21881,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-c-orm.ktx2",
    bytes: 37666,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-d-color.ktx2",
    bytes: 173001,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-d-normal.ktx2",
    bytes: 9064,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/atlas-d-orm.ktx2",
    bytes: 41655,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/ceiling-color.ktx2",
    bytes: 36689,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/ceiling-normal.ktx2",
    bytes: 72865,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/dark-panel-color.ktx2",
    bytes: 60525,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/floor-normal.ktx2",
    bytes: 20497,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/rug-normal.ktx2",
    bytes: 112627,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/walls-color.ktx2",
    bytes: 218357,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/walls-normal.ktx2",
    bytes: 64741,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex/window-color.ktx2",
    bytes: 14982,
    kind: "ktx2",
    group: "room",
    tiers: ["high", "medium"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-a-color.ktx2",
    bytes: 74423,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-a-normal.ktx2",
    bytes: 1820,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-a-orm.ktx2",
    bytes: 10891,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-b-color.ktx2",
    bytes: 82981,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-b-normal.ktx2",
    bytes: 4556,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-b-orm.ktx2",
    bytes: 13509,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-c-color.ktx2",
    bytes: 79786,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-c-normal.ktx2",
    bytes: 4682,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-c-orm.ktx2",
    bytes: 12308,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-d-color.ktx2",
    bytes: 63961,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-d-normal.ktx2",
    bytes: 2012,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/atlas-d-orm.ktx2",
    bytes: 14121,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/ceiling-color.ktx2",
    bytes: 9586,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/ceiling-normal.ktx2",
    bytes: 23766,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/dark-panel-color.ktx2",
    bytes: 16599,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/floor-normal.ktx2",
    bytes: 4781,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/rug-normal.ktx2",
    bytes: 28059,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/walls-color.ktx2",
    bytes: 72686,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/walls-normal.ktx2",
    bytes: 12451,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
  {
    url: "/story/v1/room/tex-low/window-color.ktx2",
    bytes: 6102,
    kind: "ktx2",
    group: "room",
    tiers: ["low"],
  },
];
