/**
 * Godette's baked body clips, one row per clip in the shipped clip files. Times are in seconds.
 * `face` cues drive her expression while the clip leads (setFace("auto")), `head` cues fade the
 * procedural head look while the clip owns the head, `hold` is the span a held reaction loops in,
 * and `rootMotion` clips move her placement (read it with rootMotion(); the pose itself stays put).
 * The Blender build writes this table next to the clip files; edit the build, not this file.
 */

export const GODETTE_FACES = [
  "neutral",
  "smile",
  "big_smile",
  "nervous",
  "surprised",
  "oh_no",
  "determined",
  "dizzy",
  "shy",
  "laugh",
  "pout",
  "yawn",
  "frown",
] as const;
export type GodetteFace = (typeof GODETTE_FACES)[number];

export type GodetteClipGroup = "room" | "flight" | "finale";

export type GodetteClipSpec = Readonly<{
  name: string;
  group: GodetteClipGroup;
  loop: boolean;
  duration: number;
  beats: readonly string[];
  blendIn: number;
  blendOut: number;
  face: readonly (readonly [number, GodetteFace, number])[];
  head: readonly (readonly [number, number])[];
  hold: readonly [number, number] | null;
  rootMotion: boolean;
  /** Suggested pivot pitch in degrees for the pose to read (prone glides about 80, upright 0). */
  pitch: number;
  note: string;
}>;

export const GODETTE_CLIP_LIST = [
  {
    name: "af_pose",
    group: "room",
    loop: true,
    duration: 6,
    beats: ["r-figure", "r-land"],
    blendIn: 0.3,
    blendOut: 0.3,
    face: [[0, "nervous", 1]],
    head: [[0, 0.6]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Forced toy pose, loop on the clock. Add setContext('toy'), setNervous(0.7..1), setLook({toy: 1}).",
  },
  {
    name: "af_break",
    group: "room",
    loop: false,
    duration: 5.2,
    beats: ["r-break"],
    blendIn: 0.3,
    blendOut: 0.3,
    face: [
      [0, "nervous", 1],
      [1.533, "frown", 0.7],
      [2.133, "pout", 1],
      [3.2, "yawn", 1],
      [3.8, "smile", 1],
      [4.067, "determined", 1],
      [4.4, "surprised", 1],
      [4.733, "big_smile", 1],
    ],
    head: [
      [0, 0.3],
      [1.333, 0.6],
      [3.167, 0.2],
      [3.933, 0.4],
      [5, 1],
    ],
    hold: null,
    rootMotion: true,
    pitch: 0,
    note: "Scrub by r-break progress. Root motion: 0.55 forward, down 0.0765 (the stand) at the end.",
  },
  {
    name: "look_around",
    group: "room",
    loop: false,
    duration: 4.333,
    beats: ["r-break"],
    blendIn: 0.35,
    blendOut: 0.3,
    face: [
      [0, "smile", 1],
      [0.467, "surprised", 0.6],
      [1.333, "smile", 1],
      [2.333, "surprised", 1],
      [3.333, "big_smile", 1],
    ],
    head: [
      [0, 0.35],
      [4, 0.8],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Plays after af_break inside r-break. Head is baked; give lookAt a low weight.",
  },
  {
    name: "confused_reach",
    group: "room",
    loop: false,
    duration: 3.8,
    beats: ["r-spark"],
    blendIn: 0.3,
    blendOut: 0.2,
    face: [
      [0, "surprised", 1],
      [0.667, "pout", 0.8],
      [1.467, "determined", 0.8],
      [1.867, "surprised", 0.7],
      [2.067, "pout", 1],
      [2.6, "surprised", 1],
      [3, "big_smile", 1],
    ],
    head: [
      [0, 0.5],
      [2, 0.3],
      [3, 0.7],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Ends reaching up with the left hand: dragged_yank takes over from here.",
  },
  {
    name: "dragged_yank",
    group: "room",
    loop: false,
    duration: 0.9,
    beats: ["r-dragged"],
    blendIn: 0.15,
    blendOut: 0.2,
    face: [
      [0, "surprised", 1],
      [0.133, "oh_no", 1],
    ],
    head: [[0, 0.3]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Hand the Group to the spark here: pin the hand_L socket to the spark position.",
  },
  {
    name: "dragged_dangle",
    group: "room",
    loop: true,
    duration: 2,
    beats: ["r-dragged"],
    blendIn: 0.2,
    blendOut: 0.3,
    face: [[0, "oh_no", 1]],
    head: [[0, 0.2]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Pendulum pivot: hand_L socket. Face oh_no.",
  },
  {
    name: "struggle_fly",
    group: "room",
    loop: true,
    duration: 2,
    beats: ["r-dragged", "r-learn"],
    blendIn: 0.3,
    blendOut: 0.4,
    face: [[0, "determined", 0.8]],
    head: [[0, 0.3]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Blend toward balance_glide as she learns (weights, not a cut).",
  },
  {
    name: "balance_glide",
    group: "room",
    loop: true,
    duration: 3,
    beats: ["r-learn"],
    blendIn: 0.4,
    blendOut: 0.4,
    face: [
      [0, "surprised", 0.5],
      [1.5, "smile", 1],
    ],
    head: [[0, 0.6]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Two corrections per loop. Pitch the pivot forward gradually as she gains confidence.",
  },
  {
    name: "superhero_pose",
    group: "room",
    loop: true,
    duration: 3,
    beats: ["r-learn", "r-tv"],
    blendIn: 0.4,
    blendOut: 0.4,
    face: [[0, "big_smile", 1]],
    head: [[0, 0.8]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Hover beat after the learning loop; rhymes with af_pose.",
  },
  {
    name: "fly_glide",
    group: "flight",
    loop: true,
    duration: 4,
    beats: ["r-learn", "w-1", "w-5"],
    blendIn: 0.5,
    blendOut: 0.5,
    face: [[0, "smile", 1]],
    head: [[0, 0.4]],
    hold: null,
    rootMotion: false,
    pitch: 80,
    note: "Prone glide. Pivot pitch about 80 deg; lookAt weight low (the neck is already bent back).",
  },
  {
    name: "fly_superhero",
    group: "flight",
    loop: true,
    duration: 3,
    beats: ["w-3", "w-5", "r-dive"],
    blendIn: 0.4,
    blendOut: 0.4,
    face: [
      [0, "determined", 0.6],
      [1.5, "big_smile", 0.8],
    ],
    head: [[0, 0.3]],
    hold: null,
    rootMotion: false,
    pitch: 85,
    note: "Prone, fist first. Pivot pitch about 85 deg.",
  },
  {
    name: "fly_skim",
    group: "flight",
    loop: true,
    duration: 3,
    beats: ["w-1"],
    blendIn: 0.5,
    blendOut: 0.5,
    face: [
      [0, "surprised", 0.5],
      [1.333, "smile", 1],
    ],
    head: [[0, 0.5]],
    hold: null,
    rootMotion: false,
    pitch: 25,
    note: "Upright-ish surfer stance. Pivot pitch 15 to 30 deg; face the travel direction with a yaw of about -25 deg.",
  },
  {
    name: "fly_slalom",
    group: "flight",
    loop: true,
    duration: 2,
    beats: ["w-2", "w-3"],
    blendIn: 0.4,
    blendOut: 0.4,
    face: [
      [0, "determined", 0.7],
      [1, "big_smile", 0.8],
    ],
    head: [[0, 0.2]],
    hold: null,
    rootMotion: false,
    pitch: 80,
    note: "Prone. Phase-match the path: 0.25 = hardest left, 0.75 = hardest right.",
  },
  {
    name: "fly_action",
    group: "flight",
    loop: true,
    duration: 2,
    beats: ["w-3"],
    blendIn: 0.3,
    blendOut: 0.3,
    face: [[0, "determined", 1]],
    head: [[0, 0.15]],
    hold: null,
    rootMotion: false,
    pitch: 85,
    note: "Prone, both fists first. Four kicks per loop.",
  },
  {
    name: "fly_play_spin",
    group: "flight",
    loop: true,
    duration: 2,
    beats: ["w-4"],
    blendIn: 0.4,
    blendOut: 0.4,
    face: [[0, "laugh", 1]],
    head: [[0, 0.3]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Upright or slightly tilted; spin the pivot about her long axis.",
  },
  {
    name: "barrel_tuck",
    group: "flight",
    loop: false,
    duration: 1,
    beats: ["w-2", "w-3"],
    blendIn: 0.15,
    blendOut: 0.25,
    face: [
      [0, "big_smile", 1],
      [0.2, "laugh", 1],
      [0.8, "big_smile", 1],
    ],
    head: [
      [0, 0],
      [0.867, 0.3],
    ],
    hold: null,
    rootMotion: false,
    pitch: 80,
    note: "Head look off during the roll.",
  },
  {
    name: "rift_punch_weak",
    group: "flight",
    loop: false,
    duration: 1.3,
    beats: ["w-1r"],
    blendIn: 0.25,
    blendOut: 0.3,
    face: [
      [0, "determined", 0.6],
      [0.467, "nervous", 0.8],
      [0.667, "determined", 1],
      [0.8, "pout", 1],
      [1.1, "surprised", 1],
      [1.233, "smile", 1],
    ],
    head: [[0, 0.4]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Rift 1. Upright hover; the rift appears on the punch (0.67 s).",
  },
  {
    name: "rift_punch",
    group: "flight",
    loop: false,
    duration: 1,
    beats: ["w-2r", "w-3r", "w-4r"],
    blendIn: 0.2,
    blendOut: 0.35,
    face: [
      [0, "determined", 1],
      [0.367, "big_smile", 1],
    ],
    head: [
      [0, 0.4],
      [0.667, 0.2],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Rifts 2 to 4. The rift tears open at 0.3 s; the end pose hands over to fly_superhero.",
  },
  {
    name: "rift_kick",
    group: "flight",
    loop: false,
    duration: 1.1,
    beats: ["w-4r", "w-5"],
    blendIn: 0.2,
    blendOut: 0.3,
    face: [
      [0, "determined", 1],
      [0.4, "big_smile", 1],
    ],
    head: [[0, 0.3]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Alternative rift opener; the star cracks at the kick (0.37 s).",
  },
  {
    name: "power_loss",
    group: "flight",
    loop: false,
    duration: 2.5,
    beats: ["w-loss"],
    blendIn: 0.4,
    blendOut: 0.2,
    face: [
      [0, "smile", 1],
      [0.333, "surprised", 0.6],
      [1, "frown", 1],
      [1.667, "oh_no", 0.6],
      [2.067, "oh_no", 1],
    ],
    head: [
      [0, 0.4],
      [1.667, 0.9],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Upright hover. lookAt the camera from about 1.7 s. Flicker the glow at 8 to 12 Hz from 0.3 s.",
  },
  {
    name: "fall_flail",
    group: "flight",
    loop: true,
    duration: 1,
    beats: ["w-fall", "f-cut"],
    blendIn: 0.12,
    blendOut: 0.12,
    face: [[0, "oh_no", 1]],
    head: [[0, 0.2]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Two windmills and one running stride per loop. Crossfade into land_bottom at the floor.",
  },
  {
    name: "land_bottom",
    group: "finale",
    loop: false,
    duration: 1.6,
    beats: ["f-land"],
    blendIn: 0.08,
    blendOut: 0.3,
    face: [
      [0, "oh_no", 1],
      [0.167, "surprised", 1],
      [0.4, "oh_no", 1],
      [0.8, "dizzy", 1],
    ],
    head: [
      [0, 0],
      [1.333, 0.4],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Start it when the Group reaches the floor; frames 0 to 5 hold the last 0.77 m of the fall. Group still from here.",
  },
  {
    name: "dizzy_sit",
    group: "finale",
    loop: true,
    duration: 2.5,
    beats: ["f-land"],
    blendIn: 0.3,
    blendOut: 0.3,
    face: [[0, "dizzy", 1]],
    head: [[0, 0.1]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Head circles once per loop. Socket head for the star ring.",
  },
  {
    name: "stand_up",
    group: "finale",
    loop: false,
    duration: 2.4,
    beats: ["f-stand"],
    blendIn: 0.25,
    blendOut: 0.3,
    face: [
      [0, "dizzy", 1],
      [0.533, "frown", 1],
      [1.333, "determined", 0.6],
      [1.933, "neutral", 1],
    ],
    head: [
      [0, 0.1],
      [1.867, 0.6],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "From dizzy_sit to the idle stand, feet planted where she sat.",
  },
  {
    name: "dust_off",
    group: "finale",
    loop: false,
    duration: 1.8,
    beats: ["f-stand"],
    blendIn: 0.25,
    blendOut: 0.3,
    face: [
      [0, "pout", 1],
      [0.867, "frown", 0.6],
      [1.4, "smile", 1],
      [1.6, "big_smile", 1],
    ],
    head: [
      [0, 0.2],
      [1.467, 0.8],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Ends hands on hips; lookAt the camera from 1.4 s. wave_in or idle_loop follow.",
  },
  {
    name: "wave_in",
    group: "finale",
    loop: false,
    duration: 0.6,
    beats: ["f-wave"],
    blendIn: 0.25,
    blendOut: 0.1,
    face: [
      [0, "smile", 1],
      [0.267, "big_smile", 1],
    ],
    head: [[0, 0.8]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Hands over to wave_loop at its frame 0.",
  },
  {
    name: "wave_loop",
    group: "finale",
    loop: true,
    duration: 1.333,
    beats: ["f-wave"],
    blendIn: 0.3,
    blendOut: 0.3,
    face: [[0, "big_smile", 1]],
    head: [[0, 0.8]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Two strokes per loop. Keep lookAt on the camera or the cursor.",
  },
  {
    name: "idle_loop",
    group: "finale",
    loop: true,
    duration: 6,
    beats: ["f-wave"],
    blendIn: 0.4,
    blendOut: 0.4,
    face: [[0, "smile", 1]],
    head: [[0, 1]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "The finale base loop. Reactions and yawns return to its frame 0 pose.",
  },
  {
    name: "idle_yawn",
    group: "finale",
    loop: false,
    duration: 3,
    beats: ["f-wave"],
    blendIn: 0.3,
    blendOut: 0.35,
    face: [
      [0, "neutral", 1],
      [0.4, "pout", 0.6],
      [0.667, "yawn", 1],
      [1.8, "neutral", 1],
      [2.333, "smile", 1],
    ],
    head: [
      [0, 0.6],
      [0.467, 0.1],
      [2.333, 0.7],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Idle life, starts and ends on idle_loop frame 0.",
  },
  {
    name: "idle_stretch",
    group: "finale",
    loop: false,
    duration: 3.333,
    beats: ["f-wave"],
    blendIn: 0.3,
    blendOut: 0.35,
    face: [
      [0, "neutral", 1],
      [0.533, "pout", 0.7],
      [1.333, "yawn", 0.6],
      [2.467, "big_smile", 1],
    ],
    head: [
      [0, 0.6],
      [0.533, 0.1],
      [2.667, 0.7],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Idle life, starts and ends on idle_loop frame 0.",
  },
  {
    name: "hover_shy",
    group: "finale",
    loop: false,
    duration: 2.2,
    beats: ["f-wave"],
    blendIn: 0.25,
    blendOut: 0.35,
    face: [
      [0, "smile", 1],
      [0.2, "shy", 1],
      [1.733, "smile", 1],
    ],
    head: [
      [0, 0.2],
      [1.667, 0.8],
    ],
    hold: [0.4, 1.467],
    rootMotion: false,
    pitch: 0,
    note: "Hover reaction; react('hover') holds 0.4 s to 1.47 s while the pointer stays.",
  },
  {
    name: "hover_curious",
    group: "finale",
    loop: false,
    duration: 2.2,
    beats: ["f-wave"],
    blendIn: 0.25,
    blendOut: 0.35,
    face: [
      [0, "smile", 1],
      [0.267, "surprised", 0.5],
      [0.667, "smile", 1],
      [1.467, "big_smile", 0.7],
    ],
    head: [[0, 1]],
    hold: [0.4, 1.467],
    rootMotion: false,
    pitch: 0,
    note: "Hover reaction, alternates with hover_shy. Keep lookAt on the cursor.",
  },
  {
    name: "click_giggle",
    group: "finale",
    loop: false,
    duration: 1.5,
    beats: ["f-wave"],
    blendIn: 0.12,
    blendOut: 0.3,
    face: [
      [0, "surprised", 0.6],
      [0.167, "laugh", 1],
      [1.133, "big_smile", 1],
    ],
    head: [
      [0, 0.3],
      [1.133, 0.8],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Click reaction, alternates with click_hop.",
  },
  {
    name: "click_hop",
    group: "finale",
    loop: false,
    duration: 1.4,
    beats: ["f-wave"],
    blendIn: 0.12,
    blendOut: 0.3,
    face: [
      [0, "big_smile", 1],
      [0.4, "laugh", 1],
      [1, "big_smile", 1],
    ],
    head: [[0, 0.5]],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Click reaction; the hop is in the pose, the Group stays put.",
  },
  {
    name: "poke_flinch",
    group: "finale",
    loop: false,
    duration: 0.9,
    beats: ["f-wave"],
    blendIn: 0.06,
    blendOut: 0.3,
    face: [
      [0, "surprised", 1],
      [0.333, "pout", 1],
      [0.733, "smile", 1],
    ],
    head: [
      [0, 0.3],
      [0.667, 0.8],
    ],
    hold: null,
    rootMotion: false,
    pitch: 0,
    note: "Poke reaction (a quick second click, or a tap on her head).",
  },
] as const satisfies readonly GodetteClipSpec[];

export type GodetteClip = (typeof GODETTE_CLIP_LIST)[number]["name"];
