import { choices, when } from "./helpers";
import { rt } from "./rich";
import type { FormTemplate } from "./types";

export const FEEDBACK_TEMPLATES: FormTemplate[] = [
  {
    id: "csat",
    name: "Customer satisfaction (CSAT)",
    category: "feedback",
    description:
      "Measure satisfaction with a service in under a minute, and ask why when it falls short.",
    document: {
      title: "Customer satisfaction survey",
      welcome: {
        eyebrow: "One minute",
        title: "How did we do?",
        body: rt(
          "Your honest answer helps the lab team improve the way we work with partners and students.",
        ),
        buttonLabel: "Start",
      },
      fields: [
        {
          id: "q_service",
          type: "dropdown",
          label: "Which service did you use?",
          required: true,
          options: choices("svc", [
            ["consult", "Project consultation"],
            ["dev", "App or game development"],
            ["testing", "Usability testing"],
            ["equipment", "Equipment loan"],
            ["training", "Training or workshop"],
          ]),
        },
        {
          id: "q_csat",
          type: "rating",
          label: "How satisfied are you with the service?",
          max: 5,
          ratingIcon: "smile",
          required: true,
        },
        {
          id: "q_low_reason",
          type: "checkboxes",
          label: "What fell short?",
          visibleIf: { match: "all", rules: [{ subject: "q_csat", operator: "lte", value: 3 }] },
          allowOther: true,
          options: choices("low", [
            ["speed", "It took too long"],
            ["comms", "Communication was unclear"],
            ["quality", "The result wasn't what I expected"],
            ["price", "Cost or effort was too high"],
          ]),
        },
        {
          id: "q_high_reason",
          type: "long_text",
          label: "What did you like most?",
          rows: 3,
          visibleIf: { match: "all", rules: [{ subject: "q_csat", operator: "gte", value: 4 }] },
        },
        {
          id: "q_again",
          type: "yes_no",
          label: "Would you work with us again?",
        },
        {
          id: "q_contact",
          type: "email",
          label: "Leave your email if you'd like us to follow up",
          placeholder: "name@example.com",
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Thanks for the feedback",
          body: rt("Every response is read by the team."),
        },
      ],
      design: {
        theme: "grove",
        layout: "conversational",
        background: { scene: "paper", intensity: "calm", pattern: "none", dim: 40 },
        motion: { entrance: "rise", celebration: "bloom" },
      },
      settings: { showQuestionNumbers: false },
    },
  },
  {
    id: "nps-survey",
    name: "NPS survey",
    category: "feedback",
    featured: true,
    description:
      "The classic 0 to 10 recommendation question, with a follow-up that adapts to the score.",
    document: {
      title: "Net Promoter Score survey",
      welcome: {
        eyebrow: "Quick question",
        title: "Would you recommend us?",
        body: rt("Two questions, thirty seconds."),
        buttonLabel: "Answer",
        showQuestionCount: false,
      },
      fields: [
        {
          id: "q_nps",
          type: "nps",
          label: "How likely are you to recommend MGM Laboratory to a friend or colleague?",
          min: 0,
          max: 10,
          minLabel: "Not likely",
          maxLabel: "Extremely likely",
          required: true,
        },
        {
          id: "q_detractor",
          type: "long_text",
          label: "We're sorry to hear that. What should we fix first?",
          rows: 3,
          visibleIf: { match: "all", rules: [{ subject: "q_nps", operator: "lte", value: 6 }] },
        },
        {
          id: "q_passive",
          type: "long_text",
          label: "What would make it a 10?",
          rows: 3,
          visibleIf: {
            match: "all",
            rules: [
              { subject: "q_nps", operator: "gte", value: 7 },
              { subject: "q_nps", operator: "lte", value: 8 },
            ],
          },
        },
        {
          id: "q_promoter",
          type: "long_text",
          label: "Glad to hear it. What do you value most?",
          rows: 3,
          visibleIf: { match: "all", rules: [{ subject: "q_nps", operator: "gte", value: 9 }] },
        },
        { id: "hid_segment", type: "hidden", label: "Segment", prefillParam: "segment" },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Thank you",
          body: rt("Your score helps us see where we stand."),
        },
        {
          id: "ending_promoter",
          when: { match: "all", rules: [{ subject: "q_nps", operator: "gte", value: 9 }] },
          title: "Thank you for the kind words",
          body: rt("If you'd like to share the lab with others, the buttons below make it easy."),
          showShare: true,
        },
      ],
      design: {
        theme: "signal",
        layout: "conversational",
        align: "center",
        background: { scene: "orbit", intensity: "calm", pattern: "none", dim: 40 },
        motion: { entrance: "pop", celebration: "confetti" },
      },
      settings: { showQuestionNumbers: false },
    },
  },
  {
    id: "product-feedback",
    name: "Product feedback",
    category: "feedback",
    description:
      "Collect feedback on an app or game build: usage, feature ratings, bugs and wishes.",
    document: {
      title: "Product feedback",
      welcome: {
        eyebrow: "Beta feedback",
        title: "Tell us about the build",
        body: rt(
          "You've been using an early version of one of our apps or games. Your notes shape the next release.",
        ),
        buttonLabel: "Start",
      },
      fields: [
        {
          id: "q_platform",
          type: "multiple_choice",
          label: "Which platform did you use?",
          required: true,
          optionLayout: "inline",
          options: choices("plat", [
            ["android", "Android"],
            ["ios", "iOS"],
            ["web", "Web"],
            ["pc", "PC"],
          ]),
        },
        {
          id: "q_frequency",
          type: "dropdown",
          label: "How often did you use it?",
          options: choices("freq", [
            ["daily", "Every day"],
            ["weekly", "A few times a week"],
            ["once", "Once or twice"],
          ]),
        },
        {
          id: "q_features",
          type: "matrix",
          label: "How useful is each feature?",
          rowsList: [
            { id: "row_onboarding", label: "Onboarding" },
            { id: "row_core", label: "Core experience" },
            { id: "row_sync", label: "Saving and sync" },
            { id: "row_settings", label: "Settings" },
          ],
          columnsList: [
            { id: "col_not", label: "Not useful" },
            { id: "col_some", label: "Somewhat" },
            { id: "col_very", label: "Very useful" },
          ],
        },
        {
          id: "q_priorities",
          type: "ranking",
          label: "Rank what we should improve next",
          options: choices("pri", [
            ["speed", "Speed and battery"],
            ["design", "Visual design"],
            ["content", "More content"],
            ["social", "Sharing and social features"],
            ["access", "Accessibility"],
          ]),
        },
        {
          id: "q_bug",
          type: "yes_no",
          label: "Did you run into a bug?",
        },
        {
          id: "q_bug_detail",
          type: "long_text",
          label: "What happened, and what did you expect?",
          rows: 4,
          visibleIf: when("q_bug", "equals", true),
        },
        {
          id: "q_screenshot",
          type: "image_upload",
          label: "A screenshot helps a lot",
          accept: ["image"],
          maxFiles: 3,
          maxFileMb: 10,
          visibleIf: when("q_bug", "equals", true),
        },
        {
          id: "q_satisfaction",
          type: "slider",
          label: "Overall, how happy are you with it?",
          min: 0,
          max: 100,
          step: 5,
          suffix: "%",
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Thanks for testing",
          body: rt("We read every report before the next build."),
        },
      ],
      design: {
        theme: "graphite",
        layout: "classic",
        fieldStyle: "underline",
        background: { scene: "blocks", intensity: "calm", pattern: "square", dim: 40 },
        motion: { entrance: "slide", celebration: "assemble" },
      },
    },
  },
  {
    id: "website-feedback",
    name: "Website feedback",
    category: "feedback",
    description:
      "Ask visitors what they came for, whether they found it, and how the site felt to use.",
    document: {
      title: "Website feedback",
      welcome: {
        eyebrow: "Help us improve",
        title: "How is the website working for you?",
        body: rt("Tell us what you came for and whether you found it."),
        buttonLabel: "Start",
      },
      fields: [
        {
          id: "q_goal",
          type: "multiple_choice",
          label: "What brought you to the site today?",
          required: true,
          allowOther: true,
          options: choices("goal", [
            ["projects", "Browsing projects"],
            ["research", "Research and publications"],
            ["join", "Joining the lab"],
            ["collab", "A collaboration"],
            ["events", "Events"],
          ]),
        },
        {
          id: "q_found",
          type: "yes_no",
          label: "Did you find what you were looking for?",
          required: true,
        },
        {
          id: "q_missing",
          type: "long_text",
          label: "What were you missing?",
          rows: 3,
          visibleIf: when("q_found", "equals", false),
        },
        {
          id: "q_ease",
          type: "opinion_scale",
          label: "How easy was the site to use?",
          min: 1,
          max: 7,
          minLabel: "Very hard",
          maxLabel: "Very easy",
        },
        {
          id: "q_device",
          type: "dropdown",
          label: "Which device are you on?",
          options: choices("dev", [
            ["phone", "Phone"],
            ["tablet", "Tablet"],
            ["laptop", "Laptop or desktop"],
          ]),
        },
        {
          id: "q_page",
          type: "url",
          label: "Which page is this about? (optional)",
          placeholder: "https://",
        },
        { id: "hid_page", type: "hidden", label: "Referring page", prefillParam: "page" },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Thank you",
          body: rt("We use this feedback to plan site updates."),
        },
      ],
      design: {
        theme: "slate",
        layout: "classic",
        density: "cozy",
        background: { scene: "none", intensity: "calm", pattern: "arcs", dim: 40 },
        motion: { entrance: "rise", celebration: "none" },
      },
    },
  },
  {
    id: "course-evaluation",
    name: "Course evaluation",
    category: "feedback",
    description:
      "End-of-semester evaluation of a course or lab practicum: teaching, materials and workload.",
    document: {
      title: "Course evaluation",
      welcome: {
        eyebrow: "End of semester",
        title: "Evaluate the course",
        body: rt(
          "Your answers are anonymous and help the teaching team improve the course and the practicum sessions.",
        ),
        buttonLabel: "Begin",
      },
      fields: [
        {
          id: "q_course",
          type: "dropdown",
          label: "Which course are you evaluating?",
          required: true,
          options: choices("crs", [
            ["gamedev", "Game Development"],
            ["mobile", "Mobile Application Development"],
            ["hci", "Human-Computer Interaction"],
            ["multimedia", "Multimedia Systems"],
          ]),
        },
        { id: "h_teaching", type: "heading", label: "Teaching", headingLevel: 2 },
        {
          id: "q_teaching",
          type: "matrix",
          label: "How much do you agree?",
          required: true,
          rowsList: [
            { id: "row_clear", label: "Explanations were clear" },
            { id: "row_prepared", label: "Sessions were well prepared" },
            { id: "row_feedback", label: "I got useful feedback" },
            { id: "row_available", label: "Help was available when I needed it" },
          ],
          columnsList: [
            { id: "col_sd", label: "Strongly disagree" },
            { id: "col_d", label: "Disagree" },
            { id: "col_n", label: "Neutral" },
            { id: "col_a", label: "Agree" },
            { id: "col_sa", label: "Strongly agree" },
          ],
        },
        { id: "div_1", type: "divider", label: "" },
        { id: "h_workload", type: "heading", label: "Materials and workload", headingLevel: 2 },
        {
          id: "q_materials",
          type: "rating",
          label: "Rate the course materials",
          max: 5,
          ratingIcon: "star",
        },
        {
          id: "q_hours",
          type: "number",
          label: "Hours per week you spent outside class",
          min: 0,
          max: 60,
          suffix: "h",
        },
        {
          id: "q_workload",
          type: "opinion_scale",
          label: "The workload was...",
          min: 1,
          max: 5,
          minLabel: "Too light",
          midLabel: "About right",
          maxLabel: "Too heavy",
        },
        {
          id: "q_keep",
          type: "long_text",
          label: "What should stay the same next semester?",
          rows: 3,
        },
        {
          id: "q_change",
          type: "long_text",
          label: "What should change?",
          rows: 3,
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Thank you",
          body: rt("Results are shared with the teaching team after grades are final."),
        },
      ],
      design: {
        theme: "atlas",
        layout: "classic",
        progress: "fraction",
        background: { scene: "paper", intensity: "calm", pattern: "none", dim: 40 },
        motion: { entrance: "rise", celebration: "none" },
      },
      settings: { onePerDevice: true, collectLocation: false },
    },
  },
  {
    id: "workshop-feedback",
    name: "Workshop feedback",
    category: "feedback",
    description: "Find out what participants learned, how the pace felt, and what they want next.",
    document: {
      title: "Workshop feedback",
      welcome: {
        eyebrow: "Thanks for joining",
        title: "How was the workshop?",
        body: rt("A few questions about the session. It helps the mentors a lot."),
        buttonLabel: "Start",
      },
      fields: [
        {
          id: "q_overall",
          type: "rating",
          label: "How would you rate the workshop?",
          max: 5,
          ratingIcon: "heart",
          required: true,
        },
        {
          id: "q_pace",
          type: "multiple_choice",
          label: "How was the pace?",
          optionLayout: "inline",
          options: choices("pace", [
            ["slow", "Too slow"],
            ["right", "Just right"],
            ["fast", "Too fast"],
          ]),
        },
        {
          id: "q_confidence",
          type: "slider",
          label: "How confident do you feel using what you learned?",
          min: 0,
          max: 10,
          step: 1,
          minLabel: "Not at all",
          maxLabel: "Very confident",
        },
        {
          id: "q_mentor",
          type: "opinion_scale",
          label: "How helpful were the mentors?",
          min: 1,
          max: 5,
          minLabel: "Not helpful",
          maxLabel: "Very helpful",
        },
        {
          id: "q_best",
          type: "long_text",
          label: "The best part was...",
          rows: 3,
        },
        {
          id: "q_next",
          type: "multiselect",
          label: "Which follow-up workshops would you join?",
          options: choices("next", [
            ["adv", "An advanced session on the same topic"],
            ["shaders", "Shaders and visual effects"],
            ["publish", "Publishing to app stores"],
            ["research", "Running user tests"],
          ]),
        },
        {
          id: "q_certificate",
          type: "email",
          label: "Email for your certificate of attendance",
          placeholder: "name@example.com",
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Thanks, see you next time",
          body: rt("Certificates go out within a week."),
        },
      ],
      design: {
        theme: "sunburst",
        layout: "conversational",
        background: { scene: "constellation", intensity: "lively", pattern: "none", dim: 40 },
        motion: { entrance: "pop", celebration: "confetti" },
      },
    },
  },
];
