import { choices, when } from "./helpers";
import { rt } from "./rich";
import type { FormTemplate } from "./types";

export const OPERATIONS_TEMPLATES: FormTemplate[] = [
  {
    id: "contact-form",
    name: "Contact form",
    category: "operations",
    featured: true,
    description: "A friendly general inquiry form that routes by topic and asks only what matters.",
    document: {
      title: "Contact us",
      welcome: {
        enabled: false,
        title: "Contact us",
        buttonLabel: "Start",
      },
      fields: [
        {
          id: "h_intro",
          type: "heading",
          label: "Get in touch with MGM Laboratory",
          headingLevel: 1,
        },
        {
          id: "p_intro",
          type: "paragraph",
          label: "",
          content: rt(
            "Questions about projects, research, collaboration or joining the lab: we reply within three working days.",
          ),
        },
        { id: "q_name", type: "name", label: "Your name", required: true },
        { id: "q_email", type: "email", label: "Email", required: true, width: "half" },
        { id: "q_org", type: "short_text", label: "Organisation (optional)", width: "half" },
        {
          id: "q_topic",
          type: "dropdown",
          label: "What is it about?",
          required: true,
          options: choices("topic", [
            ["collab", "Collaboration or partnership"],
            ["project", "A project inquiry"],
            ["research", "Research"],
            ["join", "Joining the lab"],
            ["media", "Press and media"],
            ["other", "Something else"],
          ]),
        },
        {
          id: "q_budget",
          type: "multiple_choice",
          label: "Is there a budget for the project?",
          visibleIf: when("q_topic", "equals", "topic_project"),
          options: choices("bud", [
            ["yes", "Yes"],
            ["planning", "Still planning"],
            ["no", "No, it's a student or community project"],
          ]),
        },
        {
          id: "q_message",
          type: "long_text",
          label: "Your message",
          required: true,
          rows: 6,
          maxLength: 3000,
        },
        {
          id: "q_attachment",
          type: "file_upload",
          label: "Attachment (optional)",
          accept: ["pdf", "document", "image", "presentation"],
          maxFiles: 2,
          maxFileMb: 15,
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Message sent",
          body: rt("Thanks for reaching out. We'll reply by email."),
          showShare: false,
        },
      ],
      design: {
        theme: "laboratory",
        layout: "classic",
        background: { scene: "orbit", intensity: "calm", pattern: "none", dim: 40 },
        motion: { entrance: "rise", celebration: "none" },
      },
      settings: {
        receipt: { enabled: true, emailFieldId: "q_email", subject: "We received your message" },
      },
    },
  },
  {
    id: "bug-report",
    name: "Bug report",
    category: "operations",
    description:
      "Structured bug reports: severity, steps to reproduce, environment and screenshots.",
    document: {
      title: "Report a bug",
      welcome: {
        eyebrow: "Quality assurance",
        title: "Found a bug?",
        body: rt("Good bug reports get fixed fast. Tell us exactly what happened."),
        buttonLabel: "Report it",
      },
      fields: [
        {
          id: "q_product",
          type: "dropdown",
          label: "Which app or game?",
          required: true,
          allowOther: true,
          options: choices("prd", [
            ["site", "The lab website"],
            ["mobile", "A mobile app"],
            ["game", "A game build"],
          ]),
        },
        {
          id: "q_title",
          type: "short_text",
          label: "Summarise the bug in one line",
          required: true,
          maxLength: 120,
        },
        {
          id: "q_severity",
          type: "multiple_choice",
          label: "How bad is it?",
          required: true,
          options: choices("sev", [
            ["blocker", "Blocker: I can't continue"],
            ["major", "Major: a feature is broken"],
            ["minor", "Minor: it works, but wrong"],
            ["cosmetic", "Cosmetic: looks off"],
          ]),
        },
        {
          id: "q_steps",
          type: "long_text",
          label: "Steps to reproduce",
          placeholder: "1. Open...\n2. Tap...\n3. See...",
          required: true,
          rows: 5,
        },
        { id: "q_expected", type: "long_text", label: "What did you expect to happen?", rows: 2 },
        {
          id: "q_platform",
          type: "checkboxes",
          label: "Where does it happen?",
          optionLayout: "grid",
          options: choices("env", [
            ["chrome", "Chrome"],
            ["safari", "Safari"],
            ["firefox", "Firefox"],
            ["android", "Android app"],
            ["ios", "iOS app"],
            ["windows", "Windows build"],
          ]),
        },
        { id: "q_version", type: "short_text", label: "Version or build number", width: "half" },
        { id: "q_when", type: "datetime", label: "When did it last happen?", width: "half" },
        {
          id: "q_screens",
          type: "file_upload",
          label: "Screenshots or a screen recording",
          accept: ["image", "video"],
          maxFiles: 5,
          maxFileMb: 50,
        },
        { id: "q_email", type: "email", label: "Your email, for follow-up questions" },
        { id: "hid_build", type: "hidden", label: "Build", prefillParam: "build" },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Thanks, report filed",
          body: rt("The team triages new bugs every morning."),
        },
        {
          id: "ending_blocker",
          when: when("q_severity", "equals", "sev_blocker"),
          title: "Flagged as urgent",
          body: rt("Blockers go straight to the developer on duty."),
        },
      ],
      design: {
        theme: "abyss",
        colorMode: "dark",
        font: "mono",
        layout: "classic",
        fieldStyle: "boxed",
        buttonShape: "rounded",
        background: { scene: "none", intensity: "calm", pattern: "square", dim: 40 },
        motion: { entrance: "slide", celebration: "none" },
      },
    },
  },
  {
    id: "feature-request",
    name: "Feature request",
    category: "operations",
    description:
      "Collect ideas with the problem they solve, how often it hurts and how much it matters.",
    document: {
      title: "Feature request",
      welcome: {
        eyebrow: "Ideas welcome",
        title: "What should we build next?",
        body: rt("Describe the problem first. The best features start with a clear need."),
        buttonLabel: "Share an idea",
      },
      fields: [
        {
          id: "q_title",
          type: "short_text",
          label: "Name your idea",
          required: true,
          maxLength: 100,
        },
        {
          id: "q_problem",
          type: "long_text",
          label: "What problem does it solve?",
          required: true,
          rows: 4,
        },
        {
          id: "q_frequency",
          type: "multiple_choice",
          label: "How often do you run into this problem?",
          options: choices("frq", [
            ["daily", "Daily"],
            ["weekly", "Weekly"],
            ["sometimes", "Now and then"],
          ]),
        },
        {
          id: "q_importance",
          type: "opinion_scale",
          label: "How important is it to you?",
          min: 1,
          max: 10,
          minLabel: "Nice to have",
          maxLabel: "Essential",
        },
        {
          id: "q_area",
          type: "multiselect",
          label: "Which parts of the product does it touch?",
          options: choices("part", [
            ["onboard", "Onboarding"],
            ["content", "Content"],
            ["social", "Social"],
            ["settings", "Settings"],
            ["perf", "Performance"],
          ]),
        },
        {
          id: "q_mockup",
          type: "image_upload",
          label: "A sketch or mockup, if you have one",
          accept: ["image"],
          maxFiles: 3,
          maxFileMb: 10,
        },
        {
          id: "q_follow",
          type: "yes_no",
          label: "May we contact you about this idea?",
        },
        {
          id: "q_email",
          type: "email",
          label: "Email",
          visibleIf: when("q_follow", "equals", true),
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Idea received",
          body: rt("We review requests at every planning session."),
        },
      ],
      design: {
        theme: "sunburst",
        layout: "conversational",
        background: { scene: "blocks", intensity: "lively", pattern: "none", dim: 40 },
        motion: { entrance: "pop", celebration: "assemble" },
      },
    },
  },
  {
    id: "equipment-booking",
    name: "Equipment booking",
    category: "operations",
    description:
      "Borrow lab equipment such as VR headsets, cameras and test devices, with dates and purpose.",
    document: {
      title: "Equipment booking",
      welcome: {
        eyebrow: "Lab equipment",
        title: "Borrow equipment",
        body: rt(
          "Members and students with an active project can borrow lab equipment for up to seven days.",
        ),
        buttonLabel: "Book equipment",
      },
      fields: [
        { id: "q_name", type: "name", label: "Borrower", required: true },
        { id: "q_email", type: "email", label: "Email", required: true, width: "half" },
        {
          id: "q_nim",
          type: "short_text",
          label: "Student or staff number",
          required: true,
          width: "half",
        },
        {
          id: "q_items",
          type: "picture_choice",
          label: "What do you need?",
          required: true,
          optionLayout: "grid",
          maxSelections: 4,
          options: [
            { id: "eq_vr", label: "VR headset" },
            { id: "eq_camera", label: "Camera kit" },
            { id: "eq_tablet", label: "Drawing tablet" },
            { id: "eq_phone", label: "Android test phone" },
            { id: "eq_mic", label: "Microphone" },
            { id: "eq_tripod", label: "Tripod and lights" },
          ],
        },
        {
          id: "q_quantity",
          type: "number",
          label: "Quantity per item",
          min: 1,
          max: 5,
          width: "half",
        },
        { id: "q_pickup", type: "date", label: "Pickup date", required: true, width: "half" },
        { id: "q_return", type: "date", label: "Return date", required: true, width: "half" },
        {
          id: "q_purpose",
          type: "long_text",
          label: "What is it for?",
          required: true,
          rows: 3,
        },
        {
          id: "c_rules",
          type: "callout",
          label: "",
          calloutTone: "warning",
          content: rt(
            "Borrowers are responsible for damage or loss. Check each item with the lab assistant at pickup.",
          ),
        },
        {
          id: "q_agree",
          type: "consent",
          label: "Loan terms",
          required: true,
          consentText: rt(
            "I will return the equipment on time and in the condition I received it.",
          ),
        },
        { id: "q_sign", type: "signature", label: "Signature", required: true },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Request sent",
          body: rt("The lab assistant confirms availability by email."),
          showShare: false,
        },
      ],
      design: {
        theme: "atlas",
        layout: "classic",
        background: { scene: "blocks", intensity: "calm", pattern: "plus", dim: 40 },
        motion: { entrance: "rise", celebration: "none" },
      },
      settings: {
        receipt: { enabled: true, emailFieldId: "q_email", subject: "Equipment booking request" },
      },
    },
  },
  {
    id: "room-booking",
    name: "Peminjaman ruang lab",
    category: "operations",
    description:
      "Formulir berbahasa Indonesia untuk meminjam ruang lab: tanggal, jam, jumlah peserta dan kebutuhan.",
    document: {
      title: "Peminjaman ruang lab",
      welcome: {
        eyebrow: "Ruang MGM Laboratory",
        title: "Pinjam ruang lab",
        body: rt(
          "Ajukan peminjaman ruang untuk rapat, kelas tambahan atau pengujian. Pengajuan minimal tiga hari sebelumnya.",
        ),
        buttonLabel: "Ajukan",
      },
      fields: [
        { id: "q_name", type: "name", label: "Nama penanggung jawab", required: true },
        { id: "q_email", type: "email", label: "Email", required: true, width: "half" },
        {
          id: "q_phone",
          type: "phone",
          label: "Nomor WhatsApp",
          defaultCountry: "ID",
          width: "half",
        },
        {
          id: "q_room",
          type: "multiple_choice",
          label: "Ruang yang ingin dipinjam",
          required: true,
          options: choices("ruang", [
            ["utama", "Ruang utama lab"],
            ["rapat", "Ruang rapat"],
            ["studio", "Studio rekaman"],
            ["uji", "Ruang uji pengguna"],
          ]),
        },
        { id: "q_date", type: "date", label: "Tanggal", required: true, width: "half" },
        { id: "q_start", type: "time", label: "Jam mulai", required: true, width: "half" },
        { id: "q_end", type: "time", label: "Jam selesai", required: true, width: "half" },
        { id: "q_people", type: "number", label: "Jumlah peserta", min: 1, max: 60, width: "half" },
        {
          id: "q_needs",
          type: "checkboxes",
          label: "Kebutuhan tambahan",
          optionLayout: "grid",
          options: choices("perlu", [
            ["proyektor", "Proyektor"],
            ["sound", "Sound system"],
            ["pc", "Komputer lab"],
            ["kamera", "Kamera perekam"],
          ]),
        },
        {
          id: "q_kegiatan",
          type: "long_text",
          label: "Deskripsi kegiatan",
          required: true,
          rows: 3,
        },
        {
          id: "q_surat",
          type: "file_upload",
          label: "Surat permohonan (jika dari luar lab)",
          accept: ["pdf"],
          maxFiles: 1,
          maxFileMb: 5,
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Pengajuan diterima",
          body: rt(
            "Kami akan mengonfirmasi ketersediaan ruang melalui email dalam satu hari kerja.",
          ),
          showShare: false,
        },
      ],
      design: {
        theme: "grove",
        layout: "classic",
        background: { scene: "paper", intensity: "calm", pattern: "domes", dim: 40 },
        motion: { entrance: "rise", celebration: "none" },
      },
      settings: {
        language: "id",
        receipt: { enabled: true, emailFieldId: "q_email", subject: "Pengajuan peminjaman ruang" },
      },
    },
  },
  {
    id: "order-request",
    name: "Order / request form",
    category: "operations",
    description:
      "Request lab services such as merchandise, printing or asset production, with quantity and delivery.",
    document: {
      title: "Order request",
      welcome: {
        eyebrow: "Lab services",
        title: "Place a request",
        body: rt(
          "Order lab merchandise or request production help. We confirm the details and cost before starting.",
        ),
        buttonLabel: "Start",
      },
      fields: [
        { id: "q_name", type: "name", label: "Your name", required: true },
        { id: "q_email", type: "email", label: "Email", required: true, width: "half" },
        { id: "q_phone", type: "phone", label: "Phone", defaultCountry: "ID", width: "half" },
        {
          id: "q_item",
          type: "multiple_choice",
          label: "What would you like?",
          required: true,
          options: choices("item", [
            ["shirt", "Lab T-shirt"],
            ["sticker", "Sticker pack"],
            ["print", "Poster printing"],
            ["asset", "3D or video asset production"],
          ]),
        },
        {
          id: "q_size",
          type: "dropdown",
          label: "Size",
          visibleIf: when("q_item", "equals", "item_shirt"),
          options: choices("size", [
            ["s", "S"],
            ["m", "M"],
            ["l", "L"],
            ["xl", "XL"],
          ]),
        },
        {
          id: "q_color",
          type: "color",
          label: "Preferred accent colour",
          visibleIf: {
            match: "any",
            rules: [
              { subject: "q_item", operator: "includes_any", value: ["item_shirt", "item_print"] },
            ],
          },
        },
        { id: "q_qty", type: "number", label: "Quantity", min: 1, max: 500, required: true },
        {
          id: "q_brief",
          type: "long_text",
          label: "Describe what you need",
          rows: 4,
          visibleIf: when("q_item", "equals", "item_asset"),
        },
        {
          id: "q_delivery",
          type: "multiple_choice",
          label: "Delivery",
          required: true,
          options: choices("dlv", [
            ["pickup", "Pick up at the lab"],
            ["ship", "Ship to my address"],
          ]),
        },
        {
          id: "q_address",
          type: "address",
          label: "Shipping address",
          required: true,
          visibleIf: when("q_delivery", "equals", "dlv_ship"),
        },
        { id: "q_needed", type: "date", label: "Needed by" },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Request received",
          body: rt("We'll email a confirmation with the total and timeline."),
        },
      ],
      design: {
        theme: "sand",
        layout: "classic",
        background: { scene: "blocks", intensity: "lively", pattern: "fans", dim: 40 },
        motion: { entrance: "pop", celebration: "confetti" },
      },
      settings: {
        receipt: { enabled: true, emailFieldId: "q_email", subject: "Your order request" },
      },
    },
  },
  {
    id: "it-support-ticket",
    name: "IT support ticket",
    category: "operations",
    description: "Log IT issues with lab computers, accounts and the network, sorted by urgency.",
    document: {
      title: "IT support ticket",
      welcome: {
        eyebrow: "Lab IT",
        title: "Open a support ticket",
        body: rt("For problems with lab computers, software licences, accounts or the network."),
        buttonLabel: "Open a ticket",
      },
      fields: [
        { id: "q_name", type: "name", label: "Your name", required: true },
        { id: "q_email", type: "email", label: "Email", required: true },
        {
          id: "q_category",
          type: "multiple_choice",
          label: "What kind of problem?",
          required: true,
          options: choices("cat", [
            ["hardware", "Hardware"],
            ["software", "Software or licence"],
            ["account", "Account or password"],
            ["network", "Network or Wi-Fi"],
          ]),
        },
        {
          id: "q_pc",
          type: "short_text",
          label: "Computer label",
          placeholder: "For example MGM-PC-07",
          visibleIf: {
            match: "any",
            rules: [
              {
                subject: "q_category",
                operator: "includes_any",
                value: ["cat_hardware", "cat_software"],
              },
            ],
          },
        },
        {
          id: "q_software",
          type: "dropdown",
          label: "Which software?",
          allowOther: true,
          visibleIf: when("q_category", "equals", "cat_software"),
          options: choices("sw", [
            ["unity", "Unity"],
            ["blender", "Blender"],
            ["adobe", "Adobe Creative Cloud"],
            ["android", "Android Studio"],
          ]),
        },
        {
          id: "q_urgency",
          type: "opinion_scale",
          label: "How urgent is it?",
          min: 1,
          max: 5,
          minLabel: "Whenever",
          maxLabel: "Right now",
          required: true,
        },
        {
          id: "q_description",
          type: "long_text",
          label: "Describe the problem",
          required: true,
          rows: 4,
        },
        {
          id: "q_screenshot",
          type: "image_upload",
          label: "Screenshot of any error message",
          accept: ["image"],
          maxFiles: 2,
          maxFileMb: 10,
        },
      ],
      endings: [
        {
          id: "ending_default",
          title: "Ticket opened",
          body: rt("The lab admin replies by email, usually the same day."),
          showShare: false,
        },
      ],
      design: {
        theme: "slate",
        layout: "classic",
        density: "cozy",
        background: { scene: "none", intensity: "calm", pattern: "none", dim: 40 },
        motion: { entrance: "rise", celebration: "none" },
      },
    },
  },
];
