name: Publish Docker Images (latest)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write
  security-events: write

jobs:
  changes:
    name: Detect Changes
    uses: ./.github/workflows/detect-changes.yml

  build:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      tag: latest
    secrets: inherit
